"""create telemetry points table

Revision ID: 575b088b1210
Revises: c9aa03729a66
Create Date: 2026-07-15 14:58:14.041028

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '575b088b1210'
down_revision: Union[str, Sequence[str], None] = 'c9aa03729a66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telemetry_points',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('race_session_id', sa.Uuid(), nullable=False),
    sa.Column('driver_id', sa.Uuid(), nullable=False),
    sa.Column('lap_id', sa.Uuid(), nullable=False),
    sa.Column('sample_index', sa.Integer(), nullable=False),
    sa.Column('relative_time_ms', sa.Integer(), nullable=False),
    sa.Column('session_time_ms', sa.Integer(), nullable=True),
    sa.Column('sampled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('speed_kph', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('rpm', sa.Integer(), nullable=True),
    sa.Column('gear', sa.Integer(), nullable=True),
    sa.Column('throttle_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('brake_applied', sa.Boolean(), nullable=True),
    sa.Column('drs', sa.Integer(), nullable=True),
    sa.Column('x', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('y', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('z', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('distance_m', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('sample_source', sa.String(length=30), nullable=True),
    sa.Column('is_interpolated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['lap_id'], ['laps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['race_session_id'], ['race_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lap_id', 'sample_index', name='uq_telemetry_points_lap_sample')
    )
    op.create_index('idx_telemetry_points_lap_time', 'telemetry_points', ['lap_id', 'relative_time_ms'], unique=False)
    op.create_index('idx_telemetry_points_session_driver', 'telemetry_points', ['race_session_id', 'driver_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_telemetry_points_session_driver', table_name='telemetry_points')
    op.drop_index('idx_telemetry_points_lap_time', table_name='telemetry_points')
    op.drop_table('telemetry_points')
    # ### end Alembic commands ###