"""add session map imports

Revision ID: 9436c56a8c22
Revises: 73679d44fdd2
Create Date: 2026-07-16 16:21:47.981552

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9436c56a8c22'
down_revision: Union[str, Sequence[str], None] = '73679d44fdd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_map_imports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('race_session_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'PARTIAL', 'FAILED', name='session_map_import_status'), nullable=False),
    sa.Column('sample_interval_ms', sa.Integer(), nullable=False),
    sa.Column('requested_driver_numbers', sa.JSON(), nullable=True),
    sa.Column('progress_percentage', sa.Integer(), nullable=False),
    sa.Column('drivers_total', sa.Integer(), nullable=False),
    sa.Column('drivers_processed', sa.Integer(), nullable=False),
    sa.Column('drivers_completed', sa.Integer(), nullable=False),
    sa.Column('drivers_partial', sa.Integer(), nullable=False),
    sa.Column('drivers_skipped', sa.Integer(), nullable=False),
    sa.Column('drivers_failed', sa.Integer(), nullable=False),
    sa.Column('samples_written', sa.Integer(), nullable=False),
    sa.Column('current_driver_number', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['race_session_id'], ['race_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_map_imports_session_status', 'session_map_imports', ['race_session_id', 'status'], unique=False)
    op.create_table('session_map_import_drivers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('map_import_id', sa.Uuid(), nullable=False),
    sa.Column('driver_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'READY', 'PARTIAL', 'SKIPPED', 'FAILED', name='session_map_driver_status'), nullable=False),
    sa.Column('raw_samples_seen', sa.Integer(), nullable=False),
    sa.Column('valid_samples', sa.Integer(), nullable=False),
    sa.Column('samples_written', sa.Integer(), nullable=False),
    sa.Column('first_sample_session_time_ms', sa.Integer(), nullable=True),
    sa.Column('last_sample_session_time_ms', sa.Integer(), nullable=True),
    sa.Column('largest_gap_ms', sa.Integer(), nullable=True),
    sa.Column('coverage_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['map_import_id'], ['session_map_imports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('map_import_id', 'driver_id', name='uq_session_map_import_driver')
    )
    op.create_index('idx_session_map_import_drivers_job_status', 'session_map_import_drivers', ['map_import_id', 'status'], unique=False)
    op.create_table('session_map_samples',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('map_import_id', sa.Uuid(), nullable=False),
    sa.Column('race_session_id', sa.Uuid(), nullable=False),
    sa.Column('driver_id', sa.Uuid(), nullable=False),
    sa.Column('lap_id', sa.Uuid(), nullable=True),
    sa.Column('session_time_ms', sa.Integer(), nullable=False),
    sa.Column('sampled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('x', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('y', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('z', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('position_status', sa.String(length=50), nullable=True),
    sa.Column('sample_source', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lap_id'], ['laps.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['map_import_id'], ['session_map_imports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['race_session_id'], ['race_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('map_import_id', 'driver_id', 'session_time_ms', name='uq_session_map_sample_time')
    )
    op.create_index('idx_session_map_samples_import_driver_time', 'session_map_samples', ['map_import_id', 'driver_id', 'session_time_ms'], unique=False)
    op.create_index('idx_session_map_samples_session_time', 'session_map_samples', ['race_session_id', 'session_time_ms'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_session_map_samples_session_time', table_name='session_map_samples')
    op.drop_index('idx_session_map_samples_import_driver_time', table_name='session_map_samples')
    op.drop_table('session_map_samples')
    op.drop_index('idx_session_map_import_drivers_job_status', table_name='session_map_import_drivers')
    op.drop_table('session_map_import_drivers')
    op.drop_index('idx_session_map_imports_session_status', table_name='session_map_imports')
    op.drop_table('session_map_imports')
    # ### end Alembic commands ###