"""create laps table

Revision ID: c9aa03729a66
Revises: d8a89daa4452
Create Date: 2026-07-15 14:38:51.751240

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9aa03729a66'
down_revision: Union[str, Sequence[str], None] = 'd8a89daa4452'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('race_session_id', sa.Uuid(), nullable=False),
    sa.Column('driver_id', sa.Uuid(), nullable=False),
    sa.Column('lap_number', sa.Integer(), nullable=False),
    sa.Column('lap_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lap_start_time_ms', sa.Integer(), nullable=True),
    sa.Column('lap_time_ms', sa.Integer(), nullable=True),
    sa.Column('sector_1_time_ms', sa.Integer(), nullable=True),
    sa.Column('sector_2_time_ms', sa.Integer(), nullable=True),
    sa.Column('sector_3_time_ms', sa.Integer(), nullable=True),
    sa.Column('speed_i1', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('speed_i2', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('speed_fl', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('speed_st', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('stint', sa.Integer(), nullable=True),
    sa.Column('compound', sa.String(length=30), nullable=True),
    sa.Column('tyre_life', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('fresh_tyre', sa.Boolean(), nullable=True),
    sa.Column('pit_in_time_ms', sa.Integer(), nullable=True),
    sa.Column('pit_out_time_ms', sa.Integer(), nullable=True),
    sa.Column('track_status', sa.String(length=50), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('is_personal_best', sa.Boolean(), nullable=True),
    sa.Column('is_accurate', sa.Boolean(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_reason', sa.Text(), nullable=True),
    sa.Column('fastf1_generated', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['race_session_id'], ['race_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_session_id', 'driver_id', 'lap_number', name='uq_laps_session_driver_lap')
    )
    op.create_index('idx_laps_session_driver', 'laps', ['race_session_id', 'driver_id'], unique=False)
    op.create_index('idx_laps_session_lap_number', 'laps', ['race_session_id', 'lap_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_laps_session_lap_number', table_name='laps')
    op.drop_index('idx_laps_session_driver', table_name='laps')
    op.drop_table('laps')
    # ### end Alembic commands ###