"""create normalized session tables

Revision ID: d8a89daa4452
Revises: c870b1bccb4a
Create Date: 2026-07-15 12:40:18.528386

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8a89daa4452'
down_revision: Union[str, Sequence[str], None] = 'c870b1bccb4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_identifier', sa.String(length=100), nullable=True),
    sa.Column('driver_number', sa.String(length=20), nullable=False),
    sa.Column('abbreviation', sa.String(length=10), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_identifier', name='uq_drivers_source_identifier')
    )
    op.create_table('meetings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('official_name', sa.String(length=255), nullable=True),
    sa.Column('country_name', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'year', 'name', name='uq_meetings_source_year_name')
    )
    op.create_table('teams',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_identifier', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('colour', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_identifier', name='uq_teams_source_identifier')
    )
    op.create_table('race_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('meeting_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('session_identifier', sa.String(length=20), nullable=False),
    sa.Column('session_type', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'session_identifier', name='uq_race_sessions_meeting_identifier')
    )
    op.create_index(op.f('ix_race_sessions_meeting_id'), 'race_sessions', ['meeting_id'], unique=False)
    op.create_table('session_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('race_session_id', sa.Uuid(), nullable=False),
    sa.Column('driver_id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('classified_position', sa.String(length=20), nullable=True),
    sa.Column('grid_position', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('points', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['race_session_id'], ['race_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_session_id', 'driver_id', name='uq_session_results_session_driver')
    )
    op.create_index(op.f('ix_session_results_driver_id'), 'session_results', ['driver_id'], unique=False)
    op.create_index(op.f('ix_session_results_race_session_id'), 'session_results', ['race_session_id'], unique=False)
    op.create_index(op.f('ix_session_results_team_id'), 'session_results', ['team_id'], unique=False)
    op.add_column('import_jobs', sa.Column('imported_session_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'import_jobs', 'race_sessions', ['imported_session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'import_jobs', type_='foreignkey')
    op.drop_column('import_jobs', 'imported_session_id')
    op.drop_index(op.f('ix_session_results_team_id'), table_name='session_results')
    op.drop_index(op.f('ix_session_results_race_session_id'), table_name='session_results')
    op.drop_index(op.f('ix_session_results_driver_id'), table_name='session_results')
    op.drop_table('session_results')
    op.drop_index(op.f('ix_race_sessions_meeting_id'), table_name='race_sessions')
    op.drop_table('race_sessions')
    op.drop_table('teams')
    op.drop_table('meetings')
    op.drop_table('drivers')
    # ### end Alembic commands ###