"""add race context timeline

Revision ID: ff583bace0fe
Revises: 9436c56a8c22
Create Date: 2026-07-21 11:19:19.086487

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff583bace0fe'
down_revision: Union[str, Sequence[str], None] = '9436c56a8c22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('race_control_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('race_session_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('session_time_ms', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=True),
    sa.Column('flag', sa.String(length=40), nullable=True),
    sa.Column('scope', sa.String(length=40), nullable=True),
    sa.Column('sector_number', sa.Integer(), nullable=True),
    sa.Column('driver_number', sa.String(length=10), nullable=True),
    sa.Column('lap_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['race_session_id'], ['race_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_race_control_events_session_occurred_at', 'race_control_events', ['race_session_id', 'occurred_at'], unique=False)
    op.create_index('idx_race_control_events_session_time', 'race_control_events', ['race_session_id', 'session_time_ms'], unique=False)
    op.create_table('weather_samples',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('race_session_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('session_time_ms', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('air_temperature_c', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('track_temperature_c', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('humidity_percent', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('pressure_hpa', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('rainfall', sa.Boolean(), nullable=True),
    sa.Column('wind_speed_mps', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('wind_direction_deg', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['race_session_id'], ['race_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_session_id', 'source', 'session_time_ms', name='uq_weather_samples_session_source_time')
    )
    op.create_index('idx_weather_samples_session_time', 'weather_samples', ['race_session_id', 'session_time_ms'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_weather_samples_session_time', table_name='weather_samples')
    op.drop_table('weather_samples')
    op.drop_index('idx_race_control_events_session_time', table_name='race_control_events')
    op.drop_index('idx_race_control_events_session_occurred_at', table_name='race_control_events')
    op.drop_table('race_control_events')
    # ### end Alembic commands ###